### PR TITLE
Adding bibliography

### PR DESCRIPTION
**Pull request by rosecers**
Update paper.md

Apply suggestions from code review

added frm figure and text

polish frm text

Added png alternative to gif

Apply suggestions from code review

Batch of suggestions from @bhelfrecht's review

Update paper/paper.md

Made svg fig png for compiling

Trying compilation with gif

Fixing some formatting

Adding a more conceptual figure for kpcovr

Fixing alphas

Fixing dscribe reference

Update paper/paper.md

Updating citations

add white spaces

Updates to paper

stashing

cur score at select

Updating nbs and figures

Updating to nb

Temp commit, edit later

Update Ice Selection.ipynb

Added modifications to the final Ice Selection plot

Update Ice Selection.ipynb

Added new figure to notebook

Updating selection figure

updated log scaling of histogram per distance

DUMMY COMMIT

Added gch to pcovr

GCH construction tests.

Added saved changes.

Added saved changes.

Updating nb

Updated NB with GCH tests and plots.

Updating after doing charge pcovr

Trying to add data files

Adding life expectancy data

finishing dch figure

Added updated figures.

Added updated notebooks for figures.

Stashing

Cleaning up who examples

Updating who data

Updating who data

Updating dpi on PCovR

Updating nbs

Cleaning up

Addressing #156, I have slimmed down the `paper-ore` branch. Should we merge this to master or have a fork?

### CODE REVIEW

**Comment by agoscinski** [comment]
We do not want this in the main branch!!! This blows ups the main branch from from roughly 10 MB to 170 MB. Also it adds a lot of files that are not required for using the package and that will most likely never be updated. You can do a fork and or probably better you do a separate repository scikit-matter-paper-ore that depends on version 0.1.3, because you can only have one personal fork and you might want to use a fork for some other stuff.

**Comment by rosecers** [comment]
Agreed! Which is why this is a draft. I just wanted to make sure to have a paper trail of the branch before forking.

**Comment by agoscinski** [comment]
I think @victorprincipe  just needs to add latest changes for the directional convex hull plot, then we can move it to different repo

**Comment by victorprincipe** [comment]
I've already added the updated notebook, so we can move it to a different repo now

**Pull request closed without merging**
